### ISSUE TITLE
Multi-GPU training

### ISSUE THREAD

**Issue by huynhthedang** [Seanlinx/mtcnn#13]
Hi Seanlinx,

Thank you for your wonderful work.
I got an error while trying to enable gpu training at

=====================ERROR=====================
Traceback (most recent call last):
  File "gen_hard_example.py", line 229, in <module>
    args.slide_window, args.shuffle, args.vis)
  File "gen_hard_example.py", line 167, in test_net
    detections = mtcnn_detector.detect_face(imdb, test_data, vis=vis)
  File "/home/dang/test/mtcnn-train/core/MtcnnDetector.py", line 456, in detect_face
    boxes, boxes_c = self.detect_pnet(im)
  File "/home/dang/test/mtcnn-train/core/MtcnnDetector.py", line 278, in detect_pnet
    cls_map, reg = self.pnet_detector.predict(im_resized)
  File "/home/dang/test/mtcnn-train/core/fcn_detector.py", line 28, in predict
    grad_req='null', aux_states=self.aux_params)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.2-py2.7-linux-x86_64.egg/mxnet/symbol.py", line 926, in bind
    ctypes.byref(handle)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.2-py2.7-linux-x86_64.egg/mxnet/base.py", line 75, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [10:57:05] src/executor/graph_executor.cc:240: Check failed: x.ctx() == default_ctx Input array is in cpu(0) while binding with ctx=gpu(0). All arguments must be in global context (gpu(0)) unless group2ctx is specified for cross-device graph.
===============================================
 
I guess the issue comes from fcn_detector.py
self.executor = self.symbol.bind(self.ctx, self.arg_params, args_grad=None,
                                         grad_req='null', aux_states=self.aux_params)

However, I checked that the self.ctx is always gpu(0) throughout the code. Maybe it binds with cpu(0) somewhere. Do you have any idea? Thanks.

**Comment by Seanlinx** [comment]
Modify line 131 in prepare_data/gen_hard_example.py:
`    args, auxs = load_param(prefix[0], epoch[0], convert=True, ctx=ctx)`
There might be some other problems since I have only tested the code on mxnet 0.7.0
