### ISSUE TITLE
"Cannot find argument 'out_grad'" when using train_P_net.py

### ISSUE THREAD

**Issue by huynhthedang** [Seanlinx/mtcnn#17]
Hi Seanlinx,

I run into this problem when trying to use train_P_.net

Called with argument:
Namespace(begin_epoch=0, dataset_path='data/mtcnn', end_epoch=16, epoch=0, frequent=200, gpu_ids='0', image_set='train_12', lr=0.01, prefix='model/pnet', pretrained='model/pnet', resume=False, root_path='data')
mtcnn_train_12 gt imdb loaded from data/cache/mtcnn_train_12_gt_roidb.pkl
append flipped images to imdb 1545850
Traceback (most recent call last):
  File "train_P_net.py", line 54, in <module>
    args.begin_epoch, args.end_epoch, args.frequent, args.lr, args.resume)
  File "train_P_net.py", line 13, in train_P_net
    sym = P_Net()
  File "/home/dang/test/mtcnn/core/symbol.py", line 38, in P_Net
    grad_scale=1, out_grad=True, name="bbox_pred")
  File "mxnet/cython/symbol.pyx", line 151, in symbol._make_atomic_symbol_function.creator (mxnet/cython/symbol.cpp:3591)
  File "mxnet/cython/base.pyi", line 36, in symbol.CALL (mxnet/cython/symbol.cpp:1624)
mxnet.base.MXNetError: Cannot find argument 'out_grad', Possible Arguments:
----------------
grad_scale : float, optional, default=1
    Scale the gradient by a float factor
, in operator LinearRegressionOutput(name="", out_grad="True", grad_scale="1")

I modified regression_output-inl.h according to mxnet_diff.patch (git apply mxnet_diff.patch), but the issue still appears. Could you please help me out? Thanks.

**Comment by Seanlinx** [comment]
You should run `make` and then reinstall python package to validate the changes.
@huynhthedang

**Comment by ZhenyuYangGithub** [comment]
@Seanlinx Did you mean run make in mxnet repo?

**Comment by zhujiang123** [comment]
@Seanlinx I meet this problem too. What should i do if my mxnet was installed by "pip install mxnet-cu80" ? I can't find make.

**Comment by twinsyssy1018** [comment]
@huynhthedang  have you solved this problem?

**Comment by twinsyssy1018** [comment]
@Seanlinx  where is the makefile ?

**Comment by tianhuangli** [comment]
@huynhthedang hi,have you solved this problem？I try to make clean and make the makefile in mxnet path and reinstall python ,however, it doesn't work...==

**Comment by anna0709** [comment]
have you solve the problem?I also meet the same problem,could you please tell how to fix it? @huynhthedang

**Comment by class8hawk** [comment]
someone have solve this problem?

**Comment by dreamersf** [comment]
someone have solve this problem?

**Comment by nihilityworld** [comment]
have anyone solved this problem?

**Comment by nihilityworld** [comment]
@Seanlinx

**Comment by dreamersf** [comment]
maybe only use facenet, facenet has mtcnn inside.

**Comment by AaronYoooooooog** [comment]
del "out_grad" in LinearRegressionOutput()

**Comment by cayla12** [comment]
have anyone solved this problem?

**Comment by AaronYoooooooog** [comment]
just remove it

**Comment by cayla12** [comment]
Please tell me "it" is what.I can not find "it" ..thanks.

**Comment by alvenchen** [comment]
just remove parameter "out_grad" in SoftmaxOutput and LinearRegressionOutput

**Comment by jkkj1630** [comment]
> just remove parameter "out_grad" in SoftmaxOutput and LinearRegressionOutput

Thanks, i'm sloved.

**Comment by poppy007** [comment]
> just remove it

Why remove it?

**Comment by fanqie03** [comment]
Why remove it?
